# cdbgen-rs example configuration.
#
# Install path:
#   /etc/cdbgen/config.toml
#
# Output directory:
#   /var/lib/cdbgen
#
# Source IDs must match: ^[a-zA-Z0-9_-]+$

[sources]

# Shared sources.
urlhaus = "https://urlhaus.abuse.ch/downloads/hostfile/"
holepl = "https://hole.cert.pl/domains/v2/domains.txt"
bebasid_filtering = "https://raw.githubusercontent.com/bebasid/bebasdns/main/dev/resources/hosts/custom-filtering-rules-blocklist"
stevenblack = "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"

# BebasDNS default profile.
oisd = "https://big.oisd.nl/unbound"
onehosts = "https://badmojr.github.io/1Hosts/Lite/unbound.conf"

# BebasDNS family profile.
alsyundawy_gambling = "https://raw.githubusercontent.com/alsyundawy/TrustPositif/refs/heads/main/alsyundawy_gambling.txt"
oisd_nsfw = "https://nsfw.oisd.nl/unbound"
bebasid_family = "https://raw.githubusercontent.com/bebasid/bebasdns/refs/heads/main/dev/resources/hosts/family-community-blacklist"
hagezi_gambling = "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/rpz/gambling.txt"

[outputs]

"urlhaus, oisd, onehosts, holepl, bebasid_filtering" = "/var/lib/cdbgen/default.cdb"

"alsyundawy_gambling, oisd_nsfw, bebasid_filtering, stevenblack, bebasid_family, holepl, hagezi_gambling" = "/var/lib/cdbgen/family.cdb"

"urlhaus, holepl, stevenblack, bebasid_filtering" = "/var/lib/cdbgen/security.cdb"
